### ISSUE TITLE
house_number is missing from parcel

### ISSUE THREAD

**Issue by Fichtme** [picqer/sendcloud-php-client#21]
Unable to create parcel, param house_number is missing.

After adding 'house_number' to the $fillable array i could create the parcel successfully. Is there a reason why this is not included? Or do i need to use another variable?

**Comment by casperbakker** [comment]
If you provide an 'address', SendCloud should split that automatically for you. It is also possible to supply a street name, but then you also need to send the house_number.

Since the seperate street and house_number is added later, we do not use it. But if you want to use it you can create a PR to support this and we will merge it.
